### ISSUE TITLE
Add a length method

### ISSUE THREAD

**Issue by iandioch** [byxor/DecayQueueJS#1]
I saw that there is a .isEmpty() method, but no method to get how many items are in the queue. If there is, it's not documented in the readme. I'm not sure what the idiomatic name for this method would be- .length(), .size(), .girth()?

**Comment by byxor** [comment]
There is already a getLength() method. I pushed it quite late last night so you may not have seen it. I might make a few aliases that do the same thing to keep everyone happy.

**Comment by byxor** [comment]
I haven't documented it yet either.
